services:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    environment:
      - MYSQL_PASSWORD=/run/secrets/db_password
      - MYSQL_ROOT_PASSWORD=/run/secrets/db_root_password
    networks:
      inception:

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    environment:
      - MYSQL_PASSWORD=/run/secrets/db_password
      - MYSQL_ROOT_PASSWORD=/run/secrets/db_root_password
    depends_on:
      - mariadb
    networks:
      inception:

  nginx:
    build: requirements/nginx/.
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
      - wordpress
    networks:
      inception:

networks:
  inception:

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/quannguy/data/DB

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/quannguy/data/WordPress

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
