services:

  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/var/www/html
    env_file:
      - .env

  web:
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    env_file:
      - .env

  db:
    build:
      dockerfile: ./mariadb/Dockerfile
    volumes:
      - mariadbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: no
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
     - .env

volumes:
  mariadbdata:

