services:

  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/var/www/html
    networks:
      - network

  web:
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    env_file:
      - .env
    networks:
      - network

  # db:
  #   image: mariadb:11.8.1-rc
  #   volumes:
  #     - mariadbdata:/var/lib/mariadb
  #   ports:
  #     - "3306:3306"
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   env_file:
  #     - .env
volumes:
  mariadbdata:
  #mariadb:

networks:
  network:
    driver: bridge
