services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/app

  db:
    image: mariadb:11.8.1-rc
    volumes:
      - mariadbdata:/var/lib/mariadb
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: docker-php
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret

volumes:
  mariadbdata:
  #mariadb:

