services:

  web:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs:ro
      - ./app:/app
    env_file:
      - .env
    # networks:
    #   - network

  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/app
    env_file:
     - .env
    #   - network

  # db:
  #   image: mariadb:11.8.1-rc
  #   volumes:
  #     - mariadbdata:/var/lib/mariadb
  #   ports:
  #     - "3306:3306"
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   env_file:
  #     - .env
volumes:
  mariadbdata:
  #mariadb:

# networks:
#   network:
#     driver: bridge
