services:

  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/var/www/html

  web:
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html

  db:
    image: mariadb:11.8.1-rc
    # build:
    #   context: .
    #   dockerfile: ./mariadb/Dockerfile
    volumes:
      - mariadbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: secret
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret

volumes:
  mariadbdata:
  #mariadb:

